#!/usr/bin/env bash

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

set -eux

readonly NPM_CMD_PATH="${NPM_CMD_PATH:-npm}"

node --version

"$NPM_CMD_PATH" install --include=dev
"$NPM_CMD_PATH" run build
"$NPM_CMD_PATH" run start
