#!/usr/bin/env bash

set -eu

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

export MIX_ENV=prod
export PORT=4600
SECRET_KEY_BASE="${SECRET_KEY_BASE?:Missing SECRET_KEY_BASE}"
DATABASE_PATH="${THIS_DIR}/../data/user.sqlite"
export SECRET_KEY_BASE DATABASE_PATH

mix deps.get --only prod
mix compile

case "${1:-''}" in
-i)
	echo 'Dropping into shell...'
	exec bash
	;;

*) ;;
esac

mix prod.setup
mix assets.deploy
exec mix phx.server
