#!/usr/bin/env bash
#
set -o pipefail
set -eu

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

.venv/bin/python -m flake8 main.py app/*.py mal_id/*.py
.venv/bin/python -m pytest ./app/db_entry_update.py
.venv/bin/python -m mypy --install-types ./mal_id/ ./app/ main.py
cd ./frontend/ && mix format
