#!/usr/bin/env bash
#
set -o pipefail
set -eu

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

flake8 main.py app/*.py src/*.py
pytest --ignore=data app/*.py src/*.py
mypy
