#!/usr/bin/env bash

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

exec rsync --exclude=anilist_cache --exclude=data.sqlite -Pavh -e ssh vultr:code/dbsentinel/data/ data
