"""add anilist model

Revision ID: 0b982be4f68b
Revises: 0022c80660ff
Create Date: 2023-01-17 18:04:05.792326

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0b982be4f68b'
down_revision = '0022c80660ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anilistid',
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('mal_id')
    )
    op.create_index(op.f('ix_anilistid_entry_type'), 'anilistid', ['entry_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anilistid_entry_type'), table_name='anilistid')
    op.drop_table('anilistid')
    # ### end Alembic commands ###
