"""anilist composite key

Revision ID: d8a872c72435
Revises: 0b982be4f68b
Create Date: 2023-01-17 18:06:33.499041

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd8a872c72435'
down_revision = '0b982be4f68b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anilistid_entry_type', table_name='anilistid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_anilistid_entry_type', 'anilistid', ['entry_type'], unique=False)
    # ### end Alembic commands ###
