"""update db model

Revision ID: e1cd63700f04
Revises: d8a872c72435
Create Date: 2023-01-17 21:26:53.909815

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "e1cd63700f04"
down_revision = "d8a872c72435"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animemetadata", sa.Column("member_count", sa.Integer(), nullable=True)
    )
    op.add_column("animemetadata", sa.Column("score", sa.Float(), nullable=True))
    op.add_column(
        "animemetadata",
        sa.Column("average_episode_duration", sa.Integer(), nullable=True),
    )
    op.add_column(
        "mangametadata", sa.Column("member_count", sa.Integer(), nullable=True)
    )
    op.add_column("mangametadata", sa.Column("score", sa.Float(), nullable=True))
    op.add_column(
        "mangametadata",
        sa.Column("average_episode_duration", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mangametadata", "average_episode_duration")
    op.drop_column("mangametadata", "score")
    op.drop_column("mangametadata", "member_count")
    op.drop_column("animemetadata", "average_episode_duration")
    op.drop_column("animemetadata", "score")
    op.drop_column("animemetadata", "member_count")
    # ### end Alembic commands ###
