"""remove score

Revision ID: eab4157eae58
Revises: e1cd63700f04
Create Date: 2023-01-17 21:44:14.290936

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "eab4157eae58"
down_revision = "e1cd63700f04"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("animemetadata", "score")
    op.drop_column("mangametadata", "score")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mangametadata", sa.Column("score", sa.FLOAT(), nullable=True))
    op.add_column("animemetadata", sa.Column("score", sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
