#!/usr/bin/env bash
# used to manage venv

set -e
set -o pipefail

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")/.."
cd "${THIS_DIR}" || exit $?

if [[ ! -d .venv ]]; then
	echo "Virtualenv doesn't exist, create it with the right pyenv version..."
	exit 1
fi

source .venv/bin/activate

case "$1" in
prod)
	alembic upgrade head && exec uvicorn app.main:app --port 5200
	;;
dev)
	exec uvicorn app.main:app --workers 1 --port 5200 --reload-exclude data
	;;
alembic)
	shift
	exec alembic "$@"
	;;
alembic_create_migration)
	shift
	exec alembic revision --autogenerate "$@"
	;;
*)
	exec "$@"
	;;
esac
