#!/usr/bin/env python3

"""
mal changed their api from api-cdn.myanimelist.net to cdn.myanimelist.net
previously I had stored the whole URL as the key in the pickledb
this script migrates the pickledb to use the path (stuff after .net) as the key instead
"""

import json
from urllib.parse import urlparse

from pathlib import Path
import click


@click.command()
@click.argument("FILE")
def main(file: Path) -> None:
    with open(file, "r") as f:
        data = json.load(f)

    new_data = {urlparse(key).path: value for key, value in data.items()}

    click.echo(json.dumps(new_data, indent=4))


if __name__ == "__main__":
    main()
